name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Use latest version
      - uses: lowlighter/metrics@3.34
        with:
          filename: github-metrics.svg
          output_action: none
          # You'll need to configure a Personal Access Token in your repository secrets named METRICS_TOKEN
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Base stats
          base: header, metadata
          base_indepth: yes
          config_timezone: Asia/Karachi
          config_display: large
          
          # Remove footer
          plugin_base_wrapper: yes
          extras_css: |
            .footer { display: none !important; }

          # Lines of code
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Languages
          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_layout: compact
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming

          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Private stats processing
          commits_authoring: "sheeraz khan, lemesherry@gmail.com, lemesherry"

          # Coding habits
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: no

      - name: Optimize SVG
        env:
          SVG_OPTIMIZER: ${{ secrets.SVG_OPTIMIZER }}
        run: |
          if [ ! -z "$SVG_OPTIMIZER" ]; then
            eval "$SVG_OPTIMIZER"
          fi

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github metrics with custom stats"
          file_pattern: github-metrics.svg
